### ISSUE TITLE
typeof 运算符引起的 babel (0 , _typeof3.default) is not a function 错误

### ISSUE THREAD

**Issue by js5323** [xyDiva/weizhang#1]
typeof 运算符引起的 babel (0 , _typeof3.default) is not a function 错误
references:
1.babel-runtime/helpers/typeof requires itself 参考@timdp的回答

你好，请问一下最终你是怎么解决这个问题的？

**Comment by xyDiva** [comment]
@js5323 
你好。查看一下node_modules/babel-runtime/typeof.js...return语句有点bug...

修改参考如下：
```javascript  
exports.default = function (obj) {
  return obj && typeof _symbol2.default !== "undefined" && obj.constructor === _symbol2.default ? "symbol" : typeof obj;
};
```

**Comment by js5323** [comment]
谢谢~已经解决！
